"""
Bridge the market-value model to the Trashium app price table.

Steps:
  1. Predict MARKET VALUE for every historical row with the trained RF.
  2. Aggregate to the app's (operational sector, waste type) grid.
  3. Apply the business formula (pricing.py) at the aggregate level:
        market_price_per_kg = median predicted market value
        logistics_per_kg    = blended logistics = sum(logistics)/sum(kg)
        price_per_kg        = payout = market_value*(1 - COMMISSION) - logistics_per_kg
        profit_per_kg       = margin = COMMISSION * market_value
  4. Fill app waste types with no dataset coverage (Glass/Organic/Mixed) from FALLBACK_RATES.
  5. Emit price_estimates_seed.{csv,sql} (schema matches the existing Supabase table).

Run (after train_models.py):  python build_price_table.py
"""
import datetime as dt
import os
import joblib
import numpy as np
import pandas as pd

import config as C
import data_prep as P


def build() -> pd.DataFrame:
    df = P.add_features(P.load_raw())
    import json
    m = json.loads((C.ARTIFACT_DIR / "metrics.json").read_text())
    best = "lr_mv.joblib" if m["best_model"] == "linear_regression" else "rf_mv.joblib"
    model = joblib.load(C.ARTIFACT_DIR / best)
    print(f"using model: {best} (lower test MAE)")
    df["pred_mv"] = model.predict(df[P.FEATURES])

    grp = df.groupby(["app_sector", "app_wastetype"])
    agg = grp.apply(lambda d: pd.Series({
        "market_price_per_kg": d["pred_mv"].median(),
        "logistics_per_kg":    d[C.COL_LOGISTICS].sum() / d[C.COL_QTY].sum(),
        "n_rows":              len(d),
    }), include_groups=False).reset_index()

    c = C.TRASHIUM_COMMISSION
    agg["price_per_kg"]  = (agg["market_price_per_kg"] * (1 - c) - agg["logistics_per_kg"]).clip(lower=0)
    agg["profit_per_kg"] = agg["market_price_per_kg"] * c
    agg["source"] = "model"
    agg = agg.rename(columns={"app_sector": "area", "app_wastetype": "waste_type"})

    # Fill the full 5 x 7 grid; missing waste types use fallback market values.
    rows = []
    have = {(r.area, r.waste_type) for r in agg.itertuples()}
    for sector in C.OPERATIONAL_SECTORS:
        for wt in C.APP_WASTE_TYPES:
            if (sector, wt) in have:
                continue
            mv = C.FALLBACK_RATES.get(wt, 3.0)
            log = 3.0
            rows.append({"area": sector, "waste_type": wt,
                         "market_price_per_kg": mv, "logistics_per_kg": log, "n_rows": 0,
                         "price_per_kg": max(mv * (1 - c) - log, 0.0),
                         "profit_per_kg": mv * c, "source": "fallback"})
    full = pd.concat([agg, pd.DataFrame(rows)], ignore_index=True)

    # Optional REAL recycler price feed: override the model's market value where the
    # feed provides one. Set env TRASHIUM_MARKET_FEED or drop data/market_prices.csv
    # (columns: waste_type, area, market_price_per_kg). Rows it covers are marked "feed".
    feed_path = os.environ.get("TRASHIUM_MARKET_FEED", str(C.ML_DIR / "data" / "market_prices.csv"))
    if os.path.exists(feed_path):
        feed = pd.read_csv(feed_path)
        fmap = {(str(r.area), str(r.waste_type)): float(r.market_price_per_kg)
                for r in feed.itertuples() if pd.notna(r.market_price_per_kg)}
        if fmap:
            m = full["__key__"] = list(zip(full["area"].astype(str), full["waste_type"].astype(str)))
            mask = full["__key__"].isin(fmap)
            full.loc[mask, "market_price_per_kg"] = full.loc[mask, "__key__"].map(fmap)
            full.loc[mask, "price_per_kg"] = (full.loc[mask, "market_price_per_kg"] * (1 - c)
                                              - full.loc[mask, "logistics_per_kg"]).clip(lower=0)
            full.loc[mask, "profit_per_kg"] = full.loc[mask, "market_price_per_kg"] * c
            full.loc[mask, "source"] = "feed"
            full = full.drop(columns="__key__")
            print(f"market feed applied to {int(mask.sum())} rows from {feed_path}")

    for col in ["price_per_kg", "logistics_per_kg", "market_price_per_kg", "profit_per_kg"]:
        full[col] = full[col].round(2)
    full["model_version"] = C.MODEL_VERSION
    full["computed_at"] = dt.datetime.utcnow().isoformat()
    return full.sort_values(["area", "waste_type"]).reset_index(drop=True)


def to_sql(tbl: pd.DataFrame) -> str:
    lines = ["-- Auto-generated by build_price_table.py - seed/refresh price_estimates",
             "BEGIN;"]
    for r in tbl.itertuples():
        lines.append(
            "INSERT INTO public.price_estimates "
            "(waste_type, area, price_per_kg, logistics_per_kg, market_price_per_kg, profit_per_kg, model_version) VALUES "
            f"('{r.waste_type}', '{r.area}', {r.price_per_kg}, {r.logistics_per_kg}, "
            f"{r.market_price_per_kg}, {r.profit_per_kg}, '{r.model_version}') "
            "ON CONFLICT (waste_type, area) DO UPDATE SET "
            "price_per_kg=EXCLUDED.price_per_kg, logistics_per_kg=EXCLUDED.logistics_per_kg, "
            "market_price_per_kg=EXCLUDED.market_price_per_kg, profit_per_kg=EXCLUDED.profit_per_kg, "
            "model_version=EXCLUDED.model_version, created_at=now();")
    lines.append("COMMIT;")
    return "\n".join(lines)


if __name__ == "__main__":
    tbl = build()
    tbl.to_csv(C.ARTIFACT_DIR / "price_estimates_seed.csv", index=False)
    (C.ARTIFACT_DIR / "price_estimates_seed.sql").write_text(to_sql(tbl))
    show = tbl[["area", "waste_type", "market_price_per_kg", "logistics_per_kg",
                "price_per_kg", "profit_per_kg", "source"]]
    print(show.to_string(index=False))
    print(f"\n{len(tbl)} rows -> artifacts/price_estimates_seed.csv + .sql")
