-- ═══════════════════════════════════════════════════════════════════════════
-- TRASHIUM — DATABASE SCHEMA
-- Regenerated from the LIVE project `fqbjjcbrxrokvdwkydze` on 2026-07-03 to end
-- the drift the QA review found (A6). This file now reflects production reality.
--
-- ⚠️ RLS is INTENTIONALLY partial during development (see DEPLOYMENT_SECURITY_CHECKLIST.md).
--    Live right now: pickup_requests RLS ON (mixed policies), global_impact RLS ON (no policy,
--    landing uses aspirational fallbacks), everything else RLS OFF. Production hardening —
--    enabling RLS everywhere, secure policies, revoking anon EXECUTE — lives in that checklist,
--    NOT here. Two policies below (trashium_final_pickups_policy / trashium_update_pickups_policy)
--    are known-insecure (reference client-writable user_metadata) and are dropped at deploy.
-- ═══════════════════════════════════════════════════════════════════════════

create extension if not exists "uuid-ossp" with schema extensions;

-- ── TABLES ─────────────────────────────────────────────────────────────────

create table if not exists public.profiles (
  id                        uuid primary key references auth.users(id),
  full_name                 text,
  email                     text unique,
  role                      text not null default 'household'
                              check (role = any (array['household','crew','admin'])),
  eco_level                 text not null default 'Seedling',
  green_credits             numeric not null default 0,
  kg_recycled               numeric not null default 0,
  co2_saved                 numeric not null default 0,
  pickups_completed         integer not null default 0,
  avatar_url                text,
  created_at                timestamptz not null default timezone('utc', now()),
  updated_at                timestamptz not null default timezone('utc', now()),
  operating_zone            text,
  pending_payout_boost_pct  numeric,
  current_streak            integer not null default 0,
  longest_streak            integer not null default 0,
  last_activity_date        date,
  streak_freezes            integer not null default 1,
  preferred_language        text default 'en'
                              check (preferred_language = any (array['en','hi','bn','ta','te','mr','gu','kn','ml','or','pa']))
  -- comment: BCP-47 code. Phase 1 supported: en, hi, bn.
);

create table if not exists public.pickup_requests (
  id                uuid primary key default extensions.uuid_generate_v4(),
  user_id           uuid not null references public.profiles(id),
  full_name         text,
  location          text,
  address           text,
  waste_type        text,
  estimated_weight  numeric,
  status            text not null default 'pending',
  -- NOTE (A5): live statuses in use are pending|accepted|collected|completed|cancelled.
  -- No CHECK constraint yet — add one at deploy and align lib/types.ts + admin CSV.
  scheduled_date    date,
  notes             text,
  estimated_price   numeric,
  created_at        timestamptz not null default timezone('utc', now()),
  updated_at        timestamptz default now(),
  time_slot         text,
  latitude          numeric,
  longitude         numeric,
  payout_override   numeric,
  override_by       uuid references public.profiles(id),
  override_at       timestamptz,
  waste_items       text[]
);

create table if not exists public.global_impact (
  id                 integer primary key default 1,
  total_kg_recycled  numeric default 0,
  total_co2_saved    numeric default 0,
  total_households   integer default 0
  -- NOTE: the landing (components/landing/impact-counter.tsx) also reads total_green_credits,
  -- which does NOT exist here — that stat falls back to a constant. Add the column + A4 rollup
  -- if you switch the landing to real live stats (see checklist §1h/§5).
);

create table if not exists public.price_estimates (
  id                   bigint generated always as identity primary key,
  waste_type           text not null,
  area                 text not null,
  price_per_kg         numeric not null,
  logistics_per_kg     numeric not null,
  market_price_per_kg  numeric not null,
  profit_per_kg        numeric not null,
  model_version        text not null,
  material_type        text not null,
  created_at           timestamptz not null default now(),
  unique (waste_type, area)   -- inferred: ml/publish_to_supabase.py upserts on (waste_type, area)
);

create table if not exists public.ma_trends (
  sector      text not null,
  waste_type  text not null,
  sma_7       numeric,
  sma_15      numeric,
  sma_30      numeric,
  sma_90      numeric,
  vol_30      numeric,
  created_at  timestamptz not null default now(),
  primary key (sector, waste_type)
);

create table if not exists public.model_metrics (
  id             bigint generated by default as identity primary key,
  model_version  text not null,
  mae            numeric not null,
  rmse           numeric not null,
  r2             numeric not null,
  created_at     timestamptz not null default now()
);

create table if not exists public.badges (
  id                text primary key,
  title             text not null,
  description       text not null,
  image_filename    text,
  category          text not null,
  unlock_type       text not null,
  unlock_threshold  numeric,
  sort_order        integer not null default 0,
  created_at        timestamptz not null default now()
);

create table if not exists public.user_badges (
  id          uuid primary key default extensions.uuid_generate_v4(),
  user_id     uuid not null references public.profiles(id),
  badge_id    text not null references public.badges(id),
  awarded_at  timestamptz not null default now()
);

create table if not exists public.marketplace_items (
  id                 uuid primary key default extensions.uuid_generate_v4(),
  name               text not null,
  description        text not null,
  tier               text not null,
  cost_credits       integer not null check (cost_credits >= 0),
  image_filename     text,
  level_requirement  integer,
  badge_requirement  text references public.badges(id),
  stock              integer,
  is_active          boolean not null default true,
  perk_type          text,
  perk_value         numeric,
  sort_order         integer not null default 0,
  created_at         timestamptz not null default now()
);

create table if not exists public.redemption_orders (
  id                  uuid primary key default extensions.uuid_generate_v4(),
  user_id             uuid not null references public.profiles(id),
  item_id             uuid not null references public.marketplace_items(id),
  item_name           text not null,
  cost_at_redemption  integer not null,
  status              text not null default 'pending',
  shipping_note       text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create table if not exists public.daily_activity (
  user_id          uuid not null references auth.users(id),
  activity_date    date not null default current_date,
  logged_in        boolean not null default false,
  segregated       boolean not null default false,
  quizzes_correct  integer not null default 0,
  quiz_strikes     integer not null default 0,
  perfect_day      boolean not null default false,
  credits_earned   numeric not null default 0,
  primary key (user_id, activity_date)
  -- NOTE: weekly_active_days is NOT a column — it is computed inside get_daily_status()/log_daily_action().
);

create table if not exists public.streak_milestone_claims (
  user_id     uuid not null references auth.users(id),
  milestone   integer not null,   -- NOTE: column is `milestone` (3/7/14/30), not `milestone_days`.
  claimed_at  timestamptz not null default now(),
  primary key (user_id, milestone)
);

-- ── FUNCTIONS (verbatim from live) ─────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email);
  RETURN new;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_modified_timestamp_column()
 RETURNS trigger LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.check_is_admin()
 RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER
AS $function$
BEGIN
  RETURN EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin');
END;
$function$;

CREATE OR REPLACE FUNCTION public.check_is_crew(authenticated_user_id uuid)
 RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = authenticated_user_id AND (role = 'crew' OR role = 'admin')
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_auth_role()
 RETURNS text LANGUAGE plpgsql SECURITY DEFINER
AS $function$
BEGIN
  RETURN (SELECT role FROM public.profiles WHERE id = auth.uid());
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_daily_status()
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
declare
  v_uid uuid := auth.uid();
  v_today date := current_date;
  v_row public.daily_activity%rowtype;
  v_prof public.profiles%rowtype;
  v_weekly int;
  v_claims int[];
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  end if;

  select * into v_prof from public.profiles where id = v_uid;
  select * into v_row from public.daily_activity where user_id = v_uid and activity_date = v_today;

  select count(distinct activity_date) into v_weekly
  from public.daily_activity
  where user_id = v_uid and activity_date > v_today - 7
    and (logged_in or segregated or quizzes_correct > 0);

  select coalesce(array_agg(milestone order by milestone), '{}') into v_claims
  from public.streak_milestone_claims where user_id = v_uid;

  return jsonb_build_object(
    'ok', true,
    'activity_date', v_today,
    'logged_in', coalesce(v_row.logged_in, false),
    'segregated', coalesce(v_row.segregated, false),
    'quizzes_correct', coalesce(v_row.quizzes_correct, 0),
    'quiz_strikes', coalesce(v_row.quiz_strikes, 0),
    'perfect_day', coalesce(v_row.perfect_day, false),
    'credits_earned', coalesce(v_row.credits_earned, 0),
    'current_streak', coalesce(v_prof.current_streak, 0),
    'longest_streak', coalesce(v_prof.longest_streak, 0),
    'streak_freezes', coalesce(v_prof.streak_freezes, 0),
    'weekly_active_days', coalesce(v_weekly, 0),
    'claimed_milestones', to_jsonb(v_claims)
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_household_leaderboard()
 RETURNS TABLE(user_id uuid, display_name text, sector text, green_credits numeric, kg_recycled numeric)
 LANGUAGE sql SECURITY DEFINER SET search_path TO 'public'
AS $function$
  select
    p.id as user_id,
    coalesce(p.full_name, 'Eco Warrior') as display_name,
    mode() within group (order by pr.location) as sector,
    p.green_credits,
    p.kg_recycled
  from profiles p
  left join pickup_requests pr
    on pr.user_id = p.id
   and pr.status in ('collected','processed','completed')
  where p.role = 'household'
  group by p.id, p.full_name, p.green_credits, p.kg_recycled;
$function$;

CREATE OR REPLACE FUNCTION public.log_daily_action(p_action text)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
declare
  v_uid    uuid := auth.uid();
  v_today  date := current_date;
  v_row    public.daily_activity%rowtype;
  v_prof   public.profiles%rowtype;
  v_logged boolean; v_segr boolean; v_qc int; v_qs int; v_perfect boolean;
  v_base int := 0; v_mult numeric := 1.0; v_award numeric := 0; v_total numeric := 0;
  v_perfect_fired boolean := false;
  v_freeze_used boolean := false;
  v_chest jsonb := null; v_chest_reward int := 0; v_chest_freeze int := 0;
  v_streak int; v_longest int; v_freezes int;
  v_weekly int;
begin
  if v_uid is null then
    return jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  end if;
  if p_action not in ('login','segregate','quiz_correct','quiz_strike') then
    return jsonb_build_object('ok', false, 'reason', 'bad_action');
  end if;

  select * into v_prof from public.profiles where id = v_uid for update;
  if not found then
    return jsonb_build_object('ok', false, 'reason', 'no_profile');
  end if;

  insert into public.daily_activity (user_id, activity_date) values (v_uid, v_today)
  on conflict (user_id, activity_date) do nothing;
  select * into v_row from public.daily_activity where user_id = v_uid and activity_date = v_today for update;

  if p_action = 'segregate' and v_row.segregated then
    return jsonb_build_object('ok', false, 'reason', 'already_segregated');
  elsif p_action = 'quiz_correct' and v_row.quizzes_correct >= 5 then
    return jsonb_build_object('ok', false, 'reason', 'quiz_cap');
  elsif p_action = 'quiz_strike' and v_row.quiz_strikes >= 2 then
    return jsonb_build_object('ok', false, 'reason', 'strike_cap');
  end if;

  v_streak  := v_prof.current_streak;
  v_longest := v_prof.longest_streak;
  v_freezes := v_prof.streak_freezes;

  if p_action in ('login','segregate','quiz_correct')
     and (v_prof.last_activity_date is distinct from v_today)
     and not (p_action = 'login' and v_row.logged_in) then
    if v_prof.last_activity_date = v_today - 1 then
      v_streak := v_streak + 1;
    elsif v_prof.last_activity_date = v_today - 2 and v_freezes > 0 then
      v_freezes := v_freezes - 1; v_streak := v_streak + 1; v_freeze_used := true;
    else
      v_streak := 1;
    end if;
    v_longest := greatest(v_longest, v_streak);
    v_prof.last_activity_date := v_today;
  end if;

  v_mult := least(2.0, 1 + 0.05 * v_streak);

  if p_action = 'login' and not v_row.logged_in then v_base := 1;
  elsif p_action = 'segregate' then v_base := 2;
  elsif p_action = 'quiz_correct' then v_base := 1;
  else v_base := 0;
  end if;
  v_award := round(v_base * v_mult);
  v_total := v_award;

  v_logged := v_row.logged_in or p_action = 'login';
  v_segr   := v_row.segregated or p_action = 'segregate';
  v_qc     := v_row.quizzes_correct + (case when p_action = 'quiz_correct' then 1 else 0 end);
  v_qs     := v_row.quiz_strikes + (case when p_action = 'quiz_strike' then 1 else 0 end);
  v_perfect := v_row.perfect_day;

  if not v_perfect and v_logged and v_segr and v_qc >= 1 then
    v_perfect := true; v_perfect_fired := true;
    v_total := v_total + round(5 * v_mult);
  end if;

  if p_action in ('login','segregate','quiz_correct') and v_streak in (3,7,14,30)
     and not exists (select 1 from public.streak_milestone_claims where user_id = v_uid and milestone = v_streak) then
    v_chest_reward := case v_streak when 3 then 10 when 7 then 20 when 14 then 40 when 30 then 100 end;
    v_chest_freeze := case when v_streak in (7,30) then 1 else 0 end;
    insert into public.streak_milestone_claims (user_id, milestone) values (v_uid, v_streak);
    v_total := v_total + v_chest_reward;
    v_freezes := v_freezes + v_chest_freeze;
    v_chest := jsonb_build_object('milestone', v_streak, 'reward', v_chest_reward, 'freeze', v_chest_freeze);
  end if;

  update public.daily_activity set
    logged_in = v_logged, segregated = v_segr, quizzes_correct = v_qc,
    quiz_strikes = v_qs, perfect_day = v_perfect, credits_earned = credits_earned + v_total
  where user_id = v_uid and activity_date = v_today;

  update public.profiles set
    green_credits = green_credits + v_total,
    current_streak = v_streak, longest_streak = v_longest,
    last_activity_date = v_prof.last_activity_date, streak_freezes = v_freezes,
    updated_at = now()
  where id = v_uid
  returning green_credits into v_prof.green_credits;

  select count(distinct activity_date) into v_weekly
  from public.daily_activity
  where user_id = v_uid and activity_date > v_today - 7
    and (logged_in or segregated or quizzes_correct > 0);

  return jsonb_build_object(
    'ok', true,
    'awarded', v_total,
    'base', v_base,
    'multiplier', v_mult,
    'current_streak', v_streak,
    'longest_streak', v_longest,
    'perfect_day', v_perfect_fired,
    'freezes', v_freezes,
    'freeze_used', v_freeze_used,
    'chest', v_chest,
    'green_credits', v_prof.green_credits,
    'caps', jsonb_build_object(
      'quizzes_correct', v_qc, 'quiz_strikes', v_qs,
      'segregated', v_segr, 'logged_in', v_logged
    ),
    'weekly_active_days', v_weekly
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.redeem_marketplace_item(p_item_id uuid)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  v_uid     uuid := auth.uid();
  v_item    public.marketplace_items%ROWTYPE;
  v_profile public.profiles%ROWTYPE;
  v_badge   public.badges%ROWTYPE;
  v_has_badge boolean;
  v_required_min int;
  v_tier_min int[] := ARRAY[0,15,40,75,120,180,250,330,420,520,640,780,940,1120,1320,1550,1820,2130,2500,3000];
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'not_authenticated');
  END IF;

  SELECT * INTO v_item FROM public.marketplace_items WHERE id = p_item_id;
  IF NOT FOUND OR v_item.is_active = false THEN
    RETURN jsonb_build_object('success', false, 'error', 'inactive');
  END IF;

  SELECT * INTO v_profile FROM public.profiles WHERE id = v_uid FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'not_authenticated');
  END IF;

  IF v_item.stock IS NOT NULL AND v_item.stock <= 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'out_of_stock');
  END IF;

  IF v_item.level_requirement IS NOT NULL THEN
    v_required_min := v_tier_min[v_item.level_requirement];
    IF v_required_min IS NULL OR v_profile.green_credits < v_required_min THEN
      RETURN jsonb_build_object('success', false, 'error', 'locked_level');
    END IF;
  END IF;

  IF v_item.badge_requirement IS NOT NULL THEN
    SELECT * INTO v_badge FROM public.badges WHERE id = v_item.badge_requirement;
    IF v_badge.unlock_type = 'credits' THEN
      v_has_badge := v_profile.green_credits >= COALESCE(v_badge.unlock_threshold, 999999999);
    ELSIF v_badge.unlock_type = 'pickups' THEN
      v_has_badge := v_profile.pickups_completed >= COALESCE(v_badge.unlock_threshold, 999999999);
    ELSE
      v_has_badge := EXISTS (
        SELECT 1 FROM public.user_badges ub
        WHERE ub.user_id = v_uid AND ub.badge_id = v_item.badge_requirement
      );
    END IF;
    IF NOT v_has_badge THEN
      RETURN jsonb_build_object('success', false, 'error', 'locked_badge');
    END IF;
  END IF;

  IF v_profile.green_credits < v_item.cost_credits THEN
    RETURN jsonb_build_object('success', false, 'error', 'insufficient_credits');
  END IF;

  -- TODO(dual-balance): deduct from a spendable wallet, not the lifetime score (D1 tradeoff).
  UPDATE public.profiles
     SET green_credits = green_credits - v_item.cost_credits,
         pending_payout_boost_pct = CASE WHEN v_item.perk_type = 'payout_boost'
                                         THEN v_item.perk_value ELSE pending_payout_boost_pct END,
         updated_at = now()
   WHERE id = v_uid;

  IF v_item.stock IS NOT NULL THEN
    UPDATE public.marketplace_items SET stock = stock - 1 WHERE id = p_item_id;
  END IF;

  INSERT INTO public.redemption_orders (user_id, item_id, item_name, cost_at_redemption, status)
  VALUES (v_uid, p_item_id, v_item.name, v_item.cost_credits, 'pending');

  RETURN jsonb_build_object('success', true, 'new_balance', v_profile.green_credits - v_item.cost_credits);
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_crew_zone(p_user_id uuid, p_zone text)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_is_admin boolean;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  END IF;
  SELECT role = 'admin' INTO v_is_admin FROM public.profiles WHERE id = v_uid;
  IF NOT coalesce(v_is_admin, false) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_admin');
  END IF;
  IF p_zone NOT IN ('Rishra','Howrah','Shyamnagar','Tarakeswar','Hugli-Chinsura') THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'invalid_zone');
  END IF;
  UPDATE public.profiles SET operating_zone = p_zone, updated_at = now()
  WHERE id = p_user_id AND role IN ('crew','collector');
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'crew_not_found');
  END IF;
  RETURN jsonb_build_object('ok', true, 'user_id', p_user_id, 'operating_zone', p_zone);
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_payout_override(p_pickup_id uuid, p_amount numeric)
 RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_is_admin boolean;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  END IF;
  SELECT role = 'admin' INTO v_is_admin FROM public.profiles WHERE id = v_uid;
  IF NOT coalesce(v_is_admin, false) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_admin');
  END IF;
  IF p_amount IS NOT NULL AND p_amount < 0 THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'invalid_amount');
  END IF;
  UPDATE public.pickup_requests
  SET payout_override = p_amount,
      override_by = CASE WHEN p_amount IS NULL THEN NULL ELSE v_uid END,
      override_at = CASE WHEN p_amount IS NULL THEN NULL ELSE now() END,
      updated_at = now()
  WHERE id = p_pickup_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'pickup_not_found');
  END IF;
  RETURN jsonb_build_object('ok', true, 'pickup_id', p_pickup_id, 'payout_override', p_amount);
END;
$function$;

-- ── TRIGGERS ───────────────────────────────────────────────────────────────

-- Auto-create a profiles row on signup.
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Keep pickup_requests.updated_at fresh.
create trigger tr_set_pickup_updated_at
  before update on public.pickup_requests
  for each row execute function public.update_modified_timestamp_column();

-- ── ROW LEVEL SECURITY (CURRENT DEV STATE — see DEPLOYMENT_SECURITY_CHECKLIST.md for production) ──
-- Dev posture: RLS mostly OFF on purpose. Only the following are enabled live right now.

alter table public.pickup_requests enable row level security;
alter table public.global_impact  enable row level security;  -- 0 policies → landing uses fallbacks (intentional in dev)

-- Secure crew/insert policies (KEEP):
create policy trashium_crew_select_pickups_policy on public.pickup_requests for select to authenticated
  using ((auth.uid() = user_id) or check_is_crew(auth.uid()));
create policy trashium_crew_update_pickups_policy on public.pickup_requests for update to authenticated
  using ((auth.uid() = user_id) or check_is_crew(auth.uid()))
  with check ((auth.uid() = user_id) or check_is_crew(auth.uid()));
create policy trashium_insert_pickups_policy on public.pickup_requests for insert to authenticated
  with check (auth.uid() = user_id);

-- ⚠️ INSECURE — reference client-writable user_metadata + a hardcoded email. DROP at deploy (checklist §1b).
create policy trashium_final_pickups_policy on public.pickup_requests for select to authenticated
  using ((auth.uid() = user_id)
    or ((auth.jwt() ->> 'email') = 'singhamartya07@gmail.com')
    or (((auth.jwt() -> 'user_metadata') ->> 'role') = 'admin'));
create policy trashium_update_pickups_policy on public.pickup_requests for update to authenticated
  using ((auth.uid() = user_id)
    or ((auth.jwt() ->> 'email') = 'singhamartya07@gmail.com')
    or (((auth.jwt() -> 'user_metadata') ->> 'role') = 'admin'))
  with check ((auth.uid() = user_id)
    or ((auth.jwt() ->> 'email') = 'singhamartya07@gmail.com')
    or (((auth.jwt() -> 'user_metadata') ->> 'role') = 'admin'));

-- RLS OFF (dev) on: profiles, price_estimates, ma_trends, model_metrics, badges, user_badges,
-- marketplace_items, redemption_orders, daily_activity, streak_milestone_claims.
-- Production policies for all of these are in DEPLOYMENT_SECURITY_CHECKLIST.md.

-- ── GRANTS (current) ───────────────────────────────────────────────────────
-- The SECURITY DEFINER RPCs are currently EXECUTE-able by anon + authenticated. At deploy, revoke anon
-- (checklist §2). The app calls them as `authenticated`.
