import type { Metadata } from "next";
import LegalPage, {
  P,
  UL,
  LI,
  Callout,
  type LegalSection,
} from "@/components/layout/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service — Trashium",
  description:
    "The terms for using Trashium — services, your responsibilities, pricing and rewards, prohibited items, and the limits of an academic demo project.",
};

const sections: LegalSection[] = [
  {
    id: "acceptance",
    heading: "Acceptance of terms",
    body: (
      <>
        <P>
          By creating an account or using Trashium, you agree to these terms. If
          you don&apos;t agree with them, please don&apos;t use the platform.
        </P>
        <Callout>
          Trashium is a final-year B.Tech capstone project running as a
          demonstration. These terms are written to be realistic for that
          context — they are not a contract with a registered company, and
          nothing here is formal legal advice.
        </Callout>
      </>
    ),
  },
  {
    id: "services",
    heading: "What Trashium does",
    body: (
      <P>
        Trashium lets households schedule doorstep pickups of dry recyclables,
        receive a transparent rate for their material, earn Green Credits, and
        redeem those credits for rewards and upcycled products. Collectors and
        admins use the platform to manage routes, verify pickups, and run
        operations across the supported areas.
      </P>
    ),
  },
  {
    id: "your-responsibilities",
    heading: "Your responsibilities",
    body: (
      <>
        <P>When you use Trashium, you agree to:</P>
        <UL>
          <LI>Provide accurate account, contact, and address details.</LI>
          <LI>
            Hand over dry, reasonably clean and segregated recyclables — not
            contaminated or mixed waste.
          </LI>
          <LI>
            Only present safe, permitted recyclable materials for collection.
          </LI>
          <LI>
            Schedule pickups honestly and be available, or reachable, at the
            chosen slot.
          </LI>
        </UL>
      </>
    ),
  },
  {
    id: "pickup-limits",
    heading: "Pickup availability & limits",
    body: (
      <P>
        Pickups depend on where you are, crew availability, and the type, amount,
        and quality of material. Service currently covers selected West Bengal
        areas — Rishra, Howrah, Shyamnagar, Tarakeswar, and Hugli-Chinsura — and
        may be limited or unavailable outside them. We may decline or reschedule a
        pickup when a crew can&apos;t reach you or the material doesn&apos;t meet
        the conditions in these terms.
      </P>
    ),
  },
  {
    id: "pricing-rewards",
    heading: "Pricing & rewards",
    body: (
      <>
        <UL>
          <LI>
            Scrap rates vary by region, material, and market conditions, and are
            generated by Trashium&apos;s pricing model rather than fixed by hand.
          </LI>
          <LI>
            Any rate or payout shown before pickup is an estimate. The final
            amount and Green Credits are based on the{" "}
            <strong>weight and quality verified at the time of pickup</strong>.
          </LI>
          <LI>
            Green Credits have value only within Trashium — for eco-levels,
            badges, and marketplace redemptions — and are not cash or a
            transferable currency.
          </LI>
        </UL>
      </>
    ),
  },
  {
    id: "prohibited",
    heading: "Prohibited items",
    body: (
      <>
        <P>Do not present the following for pickup under any circumstances:</P>
        <UL>
          <LI>Hazardous or toxic waste, including chemicals and solvents.</LI>
          <LI>Medical or biomedical waste, including sharps.</LI>
          <LI>Wet, organic, or food waste.</LI>
          <LI>Explosives, flammables, or pressurised containers.</LI>
          <LI>Illegal materials of any kind.</LI>
          <LI>Contaminated or unsafe items that could harm a collector.</LI>
        </UL>
      </>
    ),
  },
  {
    id: "admin-rights",
    heading: "Platform & admin rights",
    body: (
      <P>
        To keep the service fair and safe, admins may reject or cancel a pickup,
        adjust estimated rewards once a pickup has been verified, and suspend
        accounts that misuse the platform — for example by misreporting material
        or attempting to claim rewards dishonestly.
      </P>
    ),
  },
  {
    id: "liability",
    heading: "Limitation of liability",
    body: (
      <P>
        Trashium is provided on an &quot;as is&quot; basis as a student
        demonstration project. We make no guarantees about uninterrupted
        availability, and to the extent allowed, the project and its team
        aren&apos;t liable for losses arising from use of the platform. Use your
        own judgement around safety when handling and handing over materials.
      </P>
    ),
  },
  {
    id: "changes",
    heading: "Changes to these terms",
    body: (
      <P>
        We may update these terms as the project develops. The date at the top of
        the page reflects the latest version, and continued use of Trashium after
        a change means you accept the updated terms.
      </P>
    ),
  },
];

export default function TermsOfServicePage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="June 2026"
      intro="The ground rules for using Trashium — what the service does, what we ask of you, how pricing and rewards work, and the limits that apply to a student demonstration project."
      sections={sections}
    />
  );
}
